# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LeenHawk.GPROXY.Desktop
PackageVersion: 4.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: gproxy-desktop.exe
  PortableCommandAlias: gproxy-desktop
Scope: user
MinimumOSVersion: 10.0.17763.0
UpgradeBehavior: uninstallPrevious
Commands:
- gproxy-desktop
ReleaseDate: '2026-10-01'
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/LeenHawk/gproxy/releases/download/v4.0.0/gproxy-tauri-windows-x86_64.zip
  InstallerSha256: 999FDA912A79711E13049EB057EEEC148E224B827F3CD56A22AFDC13B011F01C
- Architecture: arm64
  InstallerUrl: https://github.com/LeenHawk/gproxy/releases/download/v4.0.0/gproxy-tauri-windows-aarch64.zip
  InstallerSha256: 070EC152A0BF5B0F17F2C6146CDC239ED9A1F44B5C91FCDEF72C923B7FF46A5B
ManifestType: installer
ManifestVersion: 1.12.0
