# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LeenHawk.GPROXY.CLI
PackageVersion: 4.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: gproxy.exe
  PortableCommandAlias: gproxy
Scope: user
MinimumOSVersion: 10.0.17763.0
UpgradeBehavior: uninstallPrevious
Commands:
- gproxy
ReleaseDate: '2026-10-01'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/LeenHawk/gproxy/releases/download/v4.0.0/gproxy-windows-x86_64.zip
  InstallerSha256: A6A6CA62ECFDE68DD067970C9C4C09D1DFFD2C3F1AEBD3914312A24C0C14AAB8
- Architecture: arm64
  InstallerUrl: https://github.com/LeenHawk/gproxy/releases/download/v4.0.0/gproxy-windows-aarch64.zip
  InstallerSha256: 6620D71B27C258CBFAA283A4C2BF159551B0BAC5B528698A60B1BA07DDC647C5
ManifestType: installer
ManifestVersion: 1.12.0
