# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: LeenHawk.GPROXY.CLI
PackageVersion: 4.0.0
PackageLocale: zh-CN
Publisher: Leen Hawk
PublisherUrl: https://github.com/LeenHawk
PublisherSupportUrl: https://github.com/LeenHawk/gproxy/issues
PackageName: GPROXY CLI
PackageUrl: https://gproxy.leenhawk.com/
License: AGPL-3.0-or-later
LicenseUrl: https://github.com/LeenHawk/gproxy/blob/main/LICENSE
ShortDescription: 提供浏览器管理控制台的开源 AI API 网关命令行版。
ManifestType: locale
ManifestVersion: 1.12.0
